import { registerCards } from "./logic.js?build=20260805-post33";

registerCards({
  "sft-k15": {
    version: "K1.5",
    title: "SFT：从续写模型到通用助手",
    oneliner: "先用约 100 万文本与 100 万图文样本建立对话、代码、数学、写作和长上下文基础，再扩大训练序列。",
    problem: [
      "预训练模型只学习下一个 token；它会续写网页，却不知道用户提问后应当给出完整、可执行的回答。",
      "如果直接进入长链 RL，基础指令格式、通用问答与视觉对话都不稳定，reward 会同时承担过多职责。",
      "长上下文还不能一步拉到 128K：模型需要先在较短序列建立稳定注意模式，再适应更长依赖。",
    ],
    bridge: "先用监督样本规定助手的基本行为，再把上下文窗口从 32K 课程式扩到 128K。",
    mechanism: [
      "文本数据约 100 万：50 万通用 QA、20 万代码、20 万数学/科学、5 千写作、2 万长上下文；另有约 100 万图文样本。",
      "第一阶段在 32K 训练 1 epoch，学习率 2×10⁻⁵→2×10⁻⁶；第二阶段 re-warmup 后在 128K 再训 1 epoch，1×10⁻⁵→1×10⁻⁶。",
      "推理题采用拒绝采样：同题生成多个候选，只把 verifier 判定正确的回答回灌为 SFT 样本。",
    ],
    visual: { type: "flow", nodes: ["预训练", "通用 SFT", "32K", "128K"], caption: "先确定助手行为，再逐级扩大可处理的上下文。" },
    formulas: ["Lₛ𝒻ₜ = −∑ₜlog πθ(yₜ|x,y<t)", "32K：η 2×10⁻⁵ → 2×10⁻⁶", "128K：re-warmup 1×10⁻⁵ → 1×10⁻⁶"],
    example: "例：一道数学题生成 8 个候选，只有 3 个最终答案通过等价验证；训练集只保留这 3 条。模型先学会按指令作答，但此时尚未系统学会规划、反思和回退。",
    deepDive: ["两类“约 100 万”不能相加成精确总量；报告给出的是规模级别。", "拒绝采样提高标签正确率，但会继承当前模型可探索到的路径边界。", "SFT 建立行为起点，不等于完成长链推理；下一阶段专门补这个缺口。"],
    next: "通用 SFT 会回答，却很少自然写出可供 RL 探索的长链；Long-CoT SFT 用少量高质量样本预热四种认知模式。",
    source: "Kimi K1.5 Technical Report §2.1–§2.2（SFT 数据组成、32K/128K 两阶段训练与拒绝采样）。",
  },
  "longcot-k15": {
    version: "K1.5",
    title: "Long-CoT SFT：让 RL 有路可走",
    oneliner: "不是灌输更多知识，而是用少量经验证的长链样本教模型规划、评估、反思与探索。",
    problem: [
      "通用 SFT 后的 rollout 通常很短；模型遇到难题会很快猜答案，RL 前几轮几乎采不到正确长链。",
      "没有正确样本，组内 reward 全为 0，梯度无法告诉模型哪种长程行为值得保留。",
      "但大量人工标注每一步推理成本过高，也会把人的固定解法写成模型唯一模板。",
    ],
    bridge: "只造一个足够好的起点：引导模型自己写长链，用最终答案 verifier 筛掉失败轨迹。",
    mechanism: [
      "从 RL 题集中取少量高质量问题，通过 prompt engineering 显式诱导规划、评估、反思、探索四种过程。",
      "候选链可以尝试错误路线，但最终答案必须通过验证；保留的是‘能纠错的完整轨迹’，不是每步都完美的教案。",
      "轻量 SFT 后，模型第一轮 RL 就能生成结构化长链，稀疏结果奖励开始有可比较样本。",
    ],
    visual: { type: "flow", nodes: ["规划", "尝试", "反思回退", "探索", "验证正确"], caption: "冷启动教的是搜索行为，不是某一道题的标准路径。" },
    formulas: ["Dwarm = {(x,y)：verify(final(y))=1}", "y 包含 Planning / Evaluation / Reflection / Exploration", "θ₀ᴿᴸ ← SFT(θₛ𝒻ₜ, Dwarm)"],
    example: "例：模型先把 2024 拆成重复的 3，随后发现题目要求正整数互异，于是回退改用连续整数求和并最终验算。错误尝试没有被剪掉，因为‘发现约束冲突并修正’正是要冷启动的能力。",
    deepDive: ["[规划] 拆分问题的一般结论是避免 1，尽量用小数…", "[尝试] 先试全用 3：但要求\"不同正整数\"，每个只能用一次。", "[反思] 等一下，约束是\"不同\"，不能重复。重新考虑。", "[探索] 那从最大的连续不同正整数往下选：n+(n-1)+...+k = 2024…", "[评估] 验算：63+62+...+k，求和公式代入…", "[继续推导，中间可能再回退一次]", "[最终答案]"],
    mechanismNext: "模型已经会展开搜索，RL 接下来用最终结果筛选路径，并用 Mirror Descent 限制每轮分布漂移。",
    next: "",
    source: "Kimi K1.5 Technical Report §2.2（Long-CoT SFT 数据生成、认知模式与验证筛选）。",
  },
  "sampling-k15": {
    version: "K1.5",
    title: "采样课程：先产生信号，再集中补弱项",
    oneliner: "Curriculum 解决早期全错无梯度，Prioritized Sampling 把后期算力转向仍未掌握的题。",
    problem: ["训练初期直接采极难题，组内回答可能全部错误，reward 没有相对差异。", "训练后期继续均匀抽题，会反复消耗算力在已稳定通过的简单题上。", "固定题序也无法响应模型能力随训练变化的事实。"],
    bridge: "先让模型在可成功区域建立能力边界，再让采样分布跟着失败率移动。",
    mechanism: ["Curriculum Sampling 从易到难扩大题目分布，保证早期 batch 更可能同时出现正负样本。", "Prioritized Sampling 跟踪题目历史成功率 sᵢ，并提高低成功率题目的抽样概率。", "两者分工：课程控制训练阶段，优先级控制同一阶段内算力落点。"],
    visual: { type: "flow", nodes: ["易题起步", "出现正负信号", "扩大难度", "聚焦低成功率"], caption: "采样不是数据搬运，而是决定梯度从哪里产生。" },
    formulas: ["pcurriculum(x|t)：difficulty(x) ≤ d(t)", "ppriority(xᵢ) ∝ 1−sᵢ", "sᵢ = historical success rate(xᵢ)"],
    example: "例：训练初期一道奥赛题 8 次采样全错，组内没有区分；先训练基础代数后，同题出现 2 条正确链。随后若另一题成功率仅 10%，它会比成功率 90% 的题被更频繁抽到。",
    deepDive: ["低成功率可能来自题目或 verifier 错误，因此优先采样前仍需做数据质检。", "成功率反比是机制表达；具体归一化与温度参数报告未完整披露。", "课程采样提高有效信号密度，但不能替代困难题本身。"],
    next: "采到可学习的轨迹后，还需要足够快地生成、暂停、验证并回收这些长 rollout。",
    source: "Kimi K1.5 Technical Report §2.3.4（Curriculum Sampling 与 Prioritized Sampling）。",
  },
  "infra-k15": {
    version: "K1.5",
    title: "长链 RL 系统：生成、续跑与验证",
    oneliner: "同步迭代保证策略一致，Partial Rollout 保存未完成轨迹，混合部署与沙箱把切换和执行成本压下来。",
    problem: ["长链生成速度慢，若训练侧等待所有轨迹完成，尾部延迟会拖住整轮更新。", "达到 token 上限就丢弃未完成轨迹，会浪费已经生成的大量上下文。", "代码 reward 必须真实执行；频繁建容器和在训练/推理框架间搬权重都会吞掉迭代时间。"],
    bridge: "把一条长 rollout 当成可暂停的作业，并让生成、训练、沙箱共享可快速切换的资源。",
    mechanism: ["同步迭代式 RL 固定‘当前策略采样 → 本轮更新 → 刷新策略’边界，避免样本版本混杂。", "Partial Rollout 在 token 上限处保存状态，下一轮继续生成，而不是把未完成轨迹清零。", "Megatron 与 vLLM 共享 GPU，切换少于 1 分钟；crun+cgroup 复用代码沙箱，吞吐约 120 containers/s。"],
    visual: { type: "flow", nodes: ["vLLM 生成", "暂停 / 续跑", "Sandbox 验证", "Megatron 更新"], caption: "算法能否成立，取决于长轨迹是否能被经济地生产与验证。" },
    formulas: ["rolloutₜ = prefix ⊕ continuationₜ₊₁", "πᵢ sample → optimize → πᵢ₊₁", "sandbox throughput ≈ 120 containers/s"],
    example: "例：32K 上限到达时，代码代理已完成 6 次调用但尚未给最终答案。系统保存前缀与环境状态，下轮从第 32K token 继续；完成后才送入沙箱跑测试并计算 reward。",
    deepDive: ["Partial Rollout 保留计算，不等于跨策略样本天然无偏；同步边界仍需明确。", "Hybrid Deployment 优化权重切换，不改变 RL 目标函数。", "120 containers/s 是报告系统指标，不应外推为任意代码任务的端到端吞吐。"],
    next: "K1.5 建立了数学/代码长链 RL 闭环；K2 要把同一闭环扩到数万种工具与开放任务。",
    source: "Kimi K1.5 Technical Report §2.5–§2.6（Partial Rollout、Hybrid Deployment、Code Sandbox）。",
  },
  "rl-k15": {
    version: "K1.5",
    title: "Online Policy Mirror Descent",
    oneliner: "reward 提高任务成功率，KL 同时限制新策略偏离参考分布的幅度。",
    problem: [
      "只追求 reward 时，一轮更新可能把少数高分回答的概率推得过高，模型很快离开原有语言能力分布。",
      "长链推理需要探索“走错—发现—回退”。如果在中间步骤做 value 估计，错误步骤会被提前惩罚，最终纠正成功的整条链也可能被拆散。",
      "因此 K1.5 不训练 value network，而是用最终结果评价整条回答，并用旧策略 πᵢ 作为每轮更新的锚点。",
    ],
    bridge: "先允许整条链探索，再用 KL 限制每轮策略漂移。",
    mechanism: [
      "先把任务结果记为 0 或 1，再用平滑的期望成功率构造可微 reward 项；否则离散指标无法直接提供稳定梯度。",
      "参数更新会同时改变任务表现与生成分布。τ·KL(πθ‖πᵢ) 为分布偏移定价，使 reward 收益必须足以补偿离开参考策略的代价。",
      "每轮结束后将 πθ 设为下一轮参考策略，并重置 optimizer，避免 Adam 的历史动量继续优化上一轮目标。",
    ],
    formulas: [
      "目标：max E[r] − τ·KL(πθ ‖ πᵢ)",
      "Lⱼ = (rⱼ − r̄ − τ·log(πθ(yⱼ|x)/πᵢ(yⱼ|x)))²",
      "r̄ = mean(r₁,…,rₖ)",
    ],
    example: "例：同题采样 4 条链，reward=[1,1,0,0]，则 r̄=0.5。两条正确链 advantage=+0.5；即使其中一条先走错再纠正，只要最终答对，整条链仍被鼓励。若它相对旧策略涨得过猛，log-ratio 项会把更新拉回。",
    deepDive: [
      "baseline 减去组内均值，使同题回答同时产生正、负 advantage，不需要额外 value network。",
      "optimizer 重置不是清空模型能力，而是清空针对旧参考策略积累的动量状态。",
      "边界：弹簧是教学类比；真实约束发生在输出概率分布，不是参数空间的欧氏距离。",
    ],
    next: "它解决了单轮更新失控，但没有解决输出越来越长、任务域过窄和主观 reward 不可靠；这三件事会在 K2 分别长出 Budget、PTX/Temp 与 Self-Critique。",
    source: "Kimi K1.5 Technical Report §2.3.2，Eq. (3)；§2.3 对 Long-CoT RL 的整体说明。",
  },
  "faithfulness-k2": {
    version: "K2",
    title: "Faithfulness Judge：把长回答拆成逐句事实检查",
    oneliner: "回答整体流畅不代表每句有依据；逐句判定把局部幻觉从整条 reward 中分离出来。",
    problem: ["长回答可能只有一句编造事实；整条判负会误伤其他正确句子，整条判正又会放过幻觉。", "开放任务缺少可执行 verifier，模型容易用自信语气掩盖证据缺口。", "RL 会反复强化被裁判放过的编造，因此漏判的代价具有累积性。"],
    bridge: "不再问整篇‘真实吗’，而是对每个可核验陈述逐句寻找依据。",
    mechanism: ["Sentence-level judge 对每句输出 faithful / unfaithful，形成比回答级标签更细的 reward。", "设计倾向宁可误杀、不可放过：误杀使模型更保守，漏判则可能让幻觉在 RL 中自强化。", "可与 helpfulness 信号共同使用，防止模型为了绝对安全只输出含糊措辞。"],
    visual: { type: "flow", nodes: ["拆句", "查依据", "逐句判定", "汇总 Reward"], caption: "局部错误只污染局部信号。" },
    formulas: ["fᵢ = Judge(sentenceᵢ, evidence) ∈ {0,1}", "rfaith = (1/n)∑ᵢfᵢ", "R = Rhelpful + β·rfaith"],
    example: "例：三句回答中，前两句正确介绍 Transformer 与论文，第三句声称 Hinton 因该论文获图灵奖。逐句裁判给 [1,1,0]，训练能够定位第三句，而不是把前两句一起视为错误。",
    deepDive: ["85–95% 的裁判精度仅在误差近似随机时可由批量平均；系统性偏差不会自动消失。", "FACTS Grounding 提供逐陈述有据性的评估思想，K2 将其转成训练 reward。", "事实性与有用性是不同轴，前者不能替代后者。"],
    next: "K2 的裁判能评开放文本；K2.5 还要让同一裁判处理图像、坐标、OCR 与计数。",
    source: "Kimi K2 Technical Report §5（sentence-level faithfulness reward）；Google DeepMind, FACTS Grounding。",
  },
  "infra-k2": {
    version: "K2",
    title: "Agentic RL 系统：把模拟工具换成可规模化环境",
    oneliner: "统一环境接口、并发沙箱、Partial Rollout 与 30 秒级 checkpoint 刷新，让多轮 agent 轨迹进入同步 RL。",
    problem: ["工具任务需要行动—观察循环，环境状态不能被普通单轮 batch 表示。", "数千至数万条并发轨迹会产生大量长尾等待与未完成状态。", "1T 参数级策略若刷新太慢，rollout 会长期使用旧权重，偏离当前训练策略。"],
    bridge: "先把环境抽象成统一 step/reset 接口，再同时缩短轨迹等待与全模型权重刷新。",
    mechanism: ["Gym-like 接口统一代码沙箱、模拟工具和真实环境，使 rollout 调度器只面对同一种交互协议。", "Agentic Rollout 系统复用 Partial Rollout，并支撑 10,000+ 并发沙箱实例。", "分布式 Checkpoint Engine 通过全集群 RDMA 广播，在约 30 秒内完成 1T 参数更新。"],
    visual: { type: "flow", nodes: ["Gym Environment", "10K+ Rollouts", "Partial State", "30s Checkpoint"], caption: "环境、轨迹、权重版本必须一起扩展。" },
    formulas: ["(oₜ₊₁,rₜ)=env.step(aₜ)", "rollouts ≥ 10,000 concurrent sandboxes", "checkpoint(1T params) ≈ 30 s"],
    example: "例：一批代理分别查工具、运行代码和等待模拟用户。未完成轨迹保留环境状态；本轮更新完成后，checkpoint engine 快速把新策略广播到生成集群，下一轮再从一致版本继续。",
    deepDive: ["统一接口减少任务接入成本，但不会消除每种环境自身的验证难题。", "高并发提升吞吐，也会放大资源争用，因此调度仍需按任务时长与沙箱负载分层。", "30 秒与 1T 是报告系统规模指标，不代表单机复制结果。"],
    next: "K2 已能规模化训练工具代理；K2.5 用 Zero-Vision SFT 把这种程序化行动模式迁移到视觉任务。",
    source: "Kimi K2 Technical Report §4–§5（Gym-like environment、Agentic Rollout、Checkpoint Engine）。",
  },
  "rl-k25": {
    version: "K2.5",
    title: "Per-token Clipping",
    oneliner: "不再用一个 ratio 代表整条回答，而是逐位置限制每个 token 的策略偏移。",
    problem: [
      "工具轨迹常有数千 token；整条序列概率是逐 token 概率连乘，一个局部极端值可能被其他位置平均掩盖。",
      "某一步工具名被推到近乎 100% 后，后续观察与推理都建立在过度自信的动作上，错误会沿轨迹放大。",
      "序列级 PPO 按整条 advantage 决定裁剪方向，无法直接回答“究竟是哪一个位置走得太远”。",
    ],
    bridge: "把安全边界从整条回答搬到每一个生成位置，让长轨迹的局部失控可以被单独截断。",
    mechanism: [
      "对每个位置 t，比较新旧策略在实际 token 上的 log probability，得到 log-ratioₜ。",
      "若 log-ratioₜ 超出 [α,β]，只把该 token 的策略梯度置零；其他位置仍可更新。",
      "约束不依赖整条 advantage 的正负，因此每一步都必须满足同一局部信赖域。",
    ],
    visual: {
      type: "token-clip",
      tokens: [
        { label: "t₁", good: true }, { label: "t₂" }, { label: "t₃" }, { label: "t₄", good: true },
        { label: "t₅" }, { label: "t₆" }, { label: "t₇" }, { label: "t₈", hot: true },
        { label: "t₉" }, { label: "t₁₀" },
      ],
    },
    formulas: [
      "ℓₜ = log πθ(yₜ|x,y<t) − log πold(yₜ|x,y<t)",
      "mₜ = 1[α ≤ ℓₜ ≤ β]",
      "∇θLₜ ← mₜ·∇θLₜ",
    ],
    example: "例：一条 10-token 的简化工具调用中，t₈ 是工具名。其 log-ratio=2.5，超过 β；该位置梯度归零。t₁…t₇ 与 t₉…t₁₀ 仍学习，所以不会因为一个越界动作把整条正确轨迹全部丢掉。",
    deepDive: [
      "使用 log-ratio 可把概率连乘变成逐位置差值，数值上更稳定，也直接对应 token 级边界。",
      "梯度归零只阻止当前 batch 继续推高该 token，不会把其概率立即恢复到旧策略。",
      "边界：图中的 t₈ 是教学案例；真实越界位置可能是工具参数、自然语言连接词或代码 token。",
    ],
    next: "局部更新稳住后，长度问题仍未消失：硬预算会诱导仓促收尾。K2.5 还需要 Toggle，在“先解会”和“再压短”之间来回切换。",
    source: "Kimi K2.5 Technical Report §3（per-token policy regularization / clipping）。",
  },
  "sft-k25": {
    version: "K2.5",
    title: "Zero-Vision SFT：不用图像先学会处理图像",
    oneliner: "SFT 阶段只给纯文本，把裁剪、OCR、表格解析写成 IPython 调用链；真实视觉信号留到 RL 接入。",
    problem: ["预训练 VLM 能看图，却未必会主动裁剪局部、调用 OCR 或用代码验证视觉结论。", "高质量视觉 CoT 要求标注者同时理解图像、工具和推理过程，难以规模化。", "若直接用真实图像做 RL，模型还要同时学工具语法与视觉判断，冷启动搜索空间过大。"],
    bridge: "把‘看见什么’暂时拿走，只监督‘遇到视觉任务时应该按什么程序行动’。",
    mechanism: ["训练样本完全由文本组成，图像对象只作为代码变量出现；模型学习 crop、OCR、parse 等 IPython 操作。", "代码调用链天然提供长程行动结构，因此不再额外设置独立 Long-CoT SFT。", "进入 RL 后接入真实图像，模型沿已学会的工具流程探索视觉结果并接受任务 reward。"],
    visual: { type: "zero-vision" },
    formulas: ["DSFT：image input = ∅", "action chain = crop → OCR → parse → answer", "π₀ᴿᴸ ← SFT(text-only tool trajectories)"],
    example: "例：问题询问图中表格第二行第三列。SFT 不展示图片，只监督 `crop_image → ocr → parse_table → rows[1][2]`；RL 才让模型对真实图片执行这条链并依据答案得分。",
    deepDive: ["Zero-Vision 不代表模型没有视觉预训练；它只描述后训练 SFT 阶段不输入图像。", "学会调用流程不保证每次裁剪坐标正确，真实视觉 RL 仍负责感知与决策校准。", "报告显示该策略优于依赖稀缺视觉 CoT 的传统冷启动，但具体迁移边界仍取决于工具覆盖。"],
    next: "冷启动完成后，文本与视觉不再分两条 RL 管线，而是按知识、推理、代码、智能体四种能力联合训练。",
    source: "Kimi K2.5 Technical Report §3（Zero-Vision SFT 与联合多模态 RL）。",
  },
  "rl-k3": {
    version: "K3",
    title: "继承 K2.5 的 Policy Optimization",
    oneliner: "K3 没有再改优化器内核，而是把创新移到任务分化、effort 课程与 on-policy 蒸馏。",
    problem: [
      "K2.5 的 per-token clipping 已能支撑长 agentic 轨迹，继续替换 policy objective 会重新引入大规模稳定性风险。",
      "K3 面临的主要矛盾已经变了：单一模型很难同时精通一次性回答、通用工具循环和代码编译—调试循环。",
      "同一任务域还要覆盖 low / high / max 三种推理强度，冲突来自训练目标组合，而非单步裁剪方式。",
    ],
    bridge: "当底层更新规则已经够稳，就冻结它，把研究预算投到“教谁、教多深、如何合并”上。",
    mechanism: [
      "K3 明确说明 policy optimization follows K2.5：per-token clipping 继续作为稳定底座。",
      "上层拆成三域×三强度九个 RL checkpoint，让每位专家只解决一组相对一致的目标。",
      "训练完成后再用 MOPD 把九位教师的行为蒸馏回一个学生，恢复部署时的单模型形态。",
    ],
    visual: { type: "k3-policy" },
    formulas: [
      "Lpolicy(K3) := Lper-token(K2.5)",
      "Experts = 3 domains × 3 efforts = 9",
      "Student ← on-policy distill(Teacher₁…Teacher₉)",
    ],
    example: "例：通用问答 low 专家被奖励简短直接；代码 max 专家允许多轮编译与修复。若强行共训，两类长度梯度会互相拉扯。K3 先分开优化，再让同一个学生学习何时采用哪种行为。",
    deepDive: [
      "“继承”只指 policy optimization 算法，不代表数据、reward、长度预算和训练课程不变。",
      "九专家是同一基础模型在不同域/强度上得到的 checkpoint，不是推理时同时激活的九个 MoE 专家。",
      "边界：将研究预算描述为转移是对报告结构的归纳，不是论文原句。",
    ],
    next: "要理解这次框架重构，下一步必须先看任务域如何从“数学/代码”扩展到工具、视觉，再分裂为三域×三强度。",
    source: "Kimi K3 Technical Report §4.1（policy optimization follows K2.5；Reasoning Effort RL；MOPD）。",
  },
  "sft-k3": {
    version: "K3",
    title: "SFT：QAT 从起点贯穿，XTML 统一智能体轨迹",
    oneliner: "先让模型在部署精度下建立复杂 agent 冷启动，再用统一标记语言表示思考、调用、观察与回答。",
    problem: ["后训练结束才量化，会突然引入舍入误差；训练、rollout 与部署看到的模型不再一致。", "多步工具、个人助理、GPU kernel 与 Web 开发轨迹结构差异大，直接拼接文本会混淆动作边界。", "K3 的九专家 RL 需要可靠冷启动，否则每个域都要重新付出早期无效探索成本。"],
    bridge: "把部署约束和轨迹语法提前到 SFT，让后续 RL 只需优化行为，不必修补表示与精度错位。",
    mechanism: ["QAT 从 SFT 贯穿 RL：MoE 专家权重模拟 MXFP4、激活模拟 MXFP8，注意力投影、共享专家和路由器等保持高精度。", "rollout 与 training 使用同一量化方案，减少 train–inference mismatch。", "XTML 用 `<think>`、`<tool_call>`、`<tool_result>`、`<answer>` 统一序列化不同 agent 轨迹。"],
    visual: { type: "k3-sft" },
    formulas: ["Wexpert → simulate(MXFP4)", "activation → simulate(MXFP8)", "trajectory = think ⊕ tool_call ⊕ tool_result ⊕ answer"],
    example: "例：个人助理先读取邮件，再查日历并更新 Notion。XTML 明确区分内在思考、工具参数、环境返回与最终回复；同一序列在低精度前向中训练，RL rollout 不必切换另一套数值格式。",
    deepDive: ["QAT 的高精度梯度更新与低精度前向模拟并不矛盾；目标是让参数适应量化误差。", "仅 MoE 专家采用最激进精度，敏感的共享组件保持高精度。", "XTML 统一表示，不等于不同任务共享同一 reward 或 token 预算。"],
    next: "冷启动之后，K3 承认单一策略无法同时覆盖三类任务与三档推理强度，于是先分化九个专家。",
    source: "Kimi K3 Technical Report §4（full-stage QAT、XTML 与复杂 agent SFT）。",
  },
  "domain-k15": {
    version: "K1.5",
    title: "数学 / 代码：可验证任务",
    oneliner: "先从答案能被规则或程序判定的任务开始，RL 才有干净、低争议的 reward。",
    problem: [
      "RL 需要大量自动评分；若每条长链都靠人工阅读，数据规模和迭代速度都无法成立。",
      "开放写作没有唯一正确答案，而数学最终答案可做等价检查，代码可以直接运行测试。",
      "客观 verifier 评价结果，不规定解题路径；模型可以探索人类没写进标准答案的正确方法。",
    ],
    bridge: "把“好不好”先缩成机器能重复判断的“对不对”，才能低成本启动长链 RL。",
    mechanism: [
      "数学 verifier 先抽取最终答案，再做符号或数值等价判断，避免只比较字符串。",
      "代码 verifier 在隔离环境运行测试用例；全部通过才获得任务成功奖励。",
      "CYaRon 管道用多个已知正确提交筛选生成用例，防止错误测试把正确程序判错。",
    ],
    visual: { type: "verifier" },
    formulas: [
      "rmath = 1[equivalent(ŷ, y*)]",
      "rcode = ∏ᵢ 1[testᵢ(program)=pass]",
      "reward 是结果函数，不是推理路径模板",
    ],
    example: "例：标准答案写 a²−4，模型写 (a+2)(a−2)。字符串不同，但展开后等价，所以数学 verifier 给 1。代码任务则把候选程序跑过全部测试；任何一例失败，整题 reward 归零。",
    deepDive: [
      "CYaRon 流程从竞赛题筛到可稳定生成测试的子集，再用多个正确提交交叉验证用例。",
      "通过测试但采用非预期算法仍应得分；这是 outcome-based RL 鼓励探索的价值。",
      "边界：测试覆盖不完备时仍可能出现 reward hacking，因此 verifier 干净不等于绝对无漏洞。",
    ],
    next: "可验证任务解决了 reward，但任务域仍很窄。K2 要进入工具使用，就必须先制造一个可交互、可评分的大规模环境。",
    source: "Kimi K1.5 Technical Report §2.3.5（math/code reward model 与 CYaRon 测试生成）。",
  },
  "domain-k2": {
    version: "K2",
    title: "工具使用：三阶段合成管道",
    oneliner: "先合成工具世界，再生成任务与评分尺，最后让 User、Agent、Tool 三方跑出可筛选轨迹。",
    problem: [
      "工具调用不是单轮问答：模型要读 spec、选择 API、填参数、观察返回，再决定下一步。",
      "真实 API 数量大、权限敏感且状态不断变化，人工录制多步轨迹既昂贵也难复现。",
      "只合成一段看似合理的调用文本不够；没有环境反馈和 Rubric，就无法知道轨迹是否真的完成任务。",
    ],
    bridge: "把缺失的数据问题改写成环境生成问题：工具、任务、交互轨迹必须成套制造。",
    mechanism: [
      "阶段一生成 Tool Spec：以真实 MCP 为种子，沿领域层级扩展出结构一致的合成工具。",
      "阶段二联合生成 Agent、任务与 Rubric，让每个任务从出生起就带有可检查的完成条件。",
      "阶段三由 User Simulator、Tool Simulator 与 Agent 交互，LLM Judge 再按 Rubric 过滤轨迹。",
    ],
    visual: { type: "tool-synthesis" },
    formulas: [
      "Dtool → generate(spec) → generate(task,rubric)",
      "trajectory = UserSim ↔ Agent ↔ ToolSim",
      "score = 4/4 → keep = schema✓ ∧ rubric✓ ∧ hack-check✓",
    ],
    example: "例：投资助手接到“查苹果近期是否有利空；股价跌破 150 就发邮件提醒”。Agent 先调 get_company_news(AAPL) 得到“供应链受关税影响 / negative”，再调 get_stock_price(AAPL) 得到 148.5 USD，满足条件后调 send_email 并报告已发送。LLM Judge 按 Rubric 给 4/4：新闻已查、股价已查、条件已判断、邮件已发且包含价格与新闻。",
    deepDive: [
      "工具：3000+ 真实 MCP 工具规格来自开源项目的既有 API；20,000+ 合成工具由 LLM 按领域层级扩展。本例的 get_company_news / get_stock_price / send_email 是从该工具库抽取的 schema。",
      "任务、Agent 角色与 Rubric：由 LLM 根据抽到的工具共同生成，并由另一 LLM Judge 先检查“这组工具是否足以完成任务”。不是为这一条轨迹人工逐字编写。",
      "执行：被训练 policy 扮演 Agent；User Simulator 与 Tool Simulator 由不同 LLM 扮演。Tool Simulator 按 schema 返回结构化新闻、价格与邮件状态。",
      "评分：Schema 校验与 Hack Detection 是程序规则；LLM Judge 按 Rubric 检查调用记录和最终结果。本例四项正向条件全通过，故 4/4 收录；若 Agent 声称已发邮件却没有 send_email 记录，Hack Detection 直接判负。",
      "真实代码执行沙箱作为外部锚点混入训练，检验合成轨迹是否迁移；合成 API 仍不能覆盖真实服务的全部异常。",
    ],
    next: "工具域证明按模态或 API 单独建管道会越来越碎。K2.5 进一步改成按能力分域，让文字和视觉在同一个推理目标下联合训练。",
    source: "Kimi K2 Technical Report §4.2（large-scale agent data synthesis：Tool、Agent/Task/Rubric、Trajectory）。",
  },
  "domain-k25": {
    version: "K2.5",
    title: "四能力域 + 联合视觉 RL",
    oneliner: "把组织轴从“输入形式”换成“模型要完成什么能力”。",
    problem: [
      "文本 RL 与视觉 RL 分开训练时，两条管道对“好推理”的定义和数据节奏彼此隔离。",
      "真实任务往往跨模态：读图表后写分析、看界面后调用工具，不能先假设问题只属于文字或图像。",
      "若视觉只在训练末尾追加，模型容易把图像当外部附件，而不是与文字共同参与推理的输入。",
    ],
    bridge: "把组织轴从“输入长什么样”换成“模型要完成什么能力”，两种模态才会共享同一套推理梯度。",
    mechanism: [
      "四域是知识、推理、代码、智能体；每域内部混合 text query 与 vision query。",
      "GRM 作为能读文字也能看图的统一裁判，使跨模态输出共享质量标准。",
      "Zero-Vision SFT 在冷启动阶段用 IPython 代码代理视觉操作，先激活“调用工具处理视觉”的行为模式。",
    ],
    visual: { type: "capability" },
    formulas: [
      "LRL = Σc∈{knowledge,reasoning,code,agent} Ec[reward]",
      "每个能力域：Dᶜ = Dtextᶜ ∪ Dvisionᶜ",
      "观察：MMLU-Pro +1.7，GPQA-Diamond +2.1，LongBench v2 +2.2",
    ],
    example: "例：同一个“比较两家公司”能力域，可同时放入纯文本年报问题和带柱状图的问题。模型共享同一套多步比较参数，因此图表训练提供的数据多样性也可能改善纯文本比较。",
    deepDive: [
      "报告观察到加入视觉 RL 后多个文本 benchmark 同步提升，说明联合训练没有简单造成模态互相稀释。",
      "边界：1–2 分提升更合理地解释为数据与推理模式多样化带来的泛化，不是视觉能力直接向文本传递。",
      "Zero-Vision SFT 的“零视觉”指冷启动 SFT 不输入真实图片，不代表后续 RL 不使用视觉数据。",
    ],
    next: "统一多模态训练扩宽了能力，但 K3 又遇到另一种冲突：一次性回答、通用 Agent、代码 Agent 的轨迹结构差异太大，需要先分域深训。",
    source: "Kimi K2.5 Technical Report §3、§3.1（joint multimodal RL、Zero-Vision SFT 与文本 benchmark 增益）。",
  },
  "domain-k3": {
    version: "K3",
    title: "三域 × 三强度：九专家课程",
    oneliner: "先让九个 checkpoint 各自在一致目标上深训，再把它们的行为蒸馏回一个学生。",
    problem: [
      "General Tasks 是一次性回答，General Agents 是行动—观察循环，Coding Agents 还要编译—报错—修复；轨迹结构并不相同。",
      "low / high / max 对输出成本和探索深度的要求相反，统一 reward 容易让简单任务过度思考、难题又被过早截断。",
      "直接在一个 checkpoint 上混合九种目标会产生梯度冲突，很难判断某项能力退化来自数据、预算还是任务域。",
    ],
    bridge: "先把冲突目标拆成九个干净课堂，每个课堂只教一种域与一种 effort。",
    mechanism: [
      "三域分别训练 General Tasks、General Agents、Coding Agents；每域再训练 low、high、max 三种强度。",
      "课程从 max 开始，再逐步退火到 high、low：先学会充分解决，再压缩成更低成本行为。",
      "九专家是同架构的 RL checkpoint；部署前通过 MOPD 合并，不是推理时并行加载九个大模型。",
    ],
    visual: { type: "expert-grid" },
    formulas: [
      "Eᵢⱼ = RL(base; domainᵢ, effortⱼ)，i,j∈{1,2,3}",
      "budget(x,effort) = τeffort·b₀(x)",
      "τmax > τhigh > τlow",
    ],
    example: "例：回答“法国首都”由 General Tasks-low 负责，直接输出即可；修复一个依赖冲突则交给 Coding Agents-max，允许多轮执行测试。两者先分开学，学生最后再学会按任务呈现对应行为。",
    deepDive: [
      "b₀(x) 是冷启动模型对题目所需长度的估计，τ 把同一基准缩放成不同 effort 上限。",
      "Coding Agents 的预算应高于一次性 General Tasks，因为环境反馈天然需要更多交互轮次。",
      "边界：九专家“课堂”是教学类比；报告描述的是域/强度专门化的训练策略与 checkpoint。",
    ],
    next: "任务拆开后，下一个瓶颈变成如何给开放式输出可靠打分：Reward 从 CoT RM 演进到 Self-Critique、跨模态 GRM，再到四步 Agentic GRM。",
    source: "Kimi K3 Technical Report §4.1（Reasoning Effort RL、domain-specific training、nine experts）；§4.1.3（Multi-Teacher On-Policy Distillation）。",
  },
  "env-k3": {
    version: "K3",
    title: "五类 Agentic 任务：从信息搜索到 GPU Kernel 优化",
    oneliner: "用白盒环境与知识图谱合成机制，制造五类覆盖不同真实工作形态的训练任务。",
    problem: ["九专家如果仍训练在短问答上，只会得到九个相似 checkpoint，无法形成 agentic 分工。", "真实专业工作往往没有参考轨迹，只有最终交付物与过程约束；模仿标准答案无法覆盖多条可行路径。", "环境越复杂，模型越容易缓存结果、绕过执行器或利用 benchmark 漏洞骗取 reward。"],
    bridge: "不预写唯一解法，而是提供可组合工具、真实反馈与隐藏验收，让策略自己发现工作流。",
    mechanism: ["统一白盒 harness 动态组合浏览器、文件系统、代码执行器等模块；同一基础设施可实例化 Kimi Code、Claude Code、Codex、OpenClaw、Hermes 等任务形态。", "知识图谱由 Agent 递归扩展成自演化 DAG，再从相邻细粒度节点合成专业任务；AET 用 verify-in-the-loop 评价无参考轨迹的执行过程。", "训练覆盖 GPU Kernel、跨多日 Personal Assistant、容器化 Web 开发；公开/隐藏 verifier 与持续更新的 hack detector 防止投机。"],
    visual: { type: "k3-environment" },
    formulas: ["task = compose(DAG nodes, harness modules)", "rkernel=0 if error>ε；≈0.5 at expert；→1 near roofline", "success = public✓ ∧ hidden✓ ∧ anti-hack✓"],
    example: "例：GPU kernel 任务先检查数值误差，再测吞吐；缓存输入、CUDA graph replay 或偷偷降精度即使更快，也会被 anti-hack 判负。另一个 AET 可让代理自行分解投行分析任务，只按中间检查与最终交付物验收。",
    deepDive: ["Personal Assistant 轨迹可跨多天、多应用并包含数千次工具调用，单条上下文达到百万 token 量级。", "Web 开发在容器中支持多 scaffold，并结合确定性检查与模型评判；报告展示的特定完成率属于对应任务集。", "AgentENV、KV write-back 与 auto-throttling 属于支撑这些环境的基础设施，不改变任务 reward 定义。"],
    next: "环境把九位专家教出差异，但九个完整 checkpoint 无法经济部署；MOPD 接着把能力合回一个学生。",
    source: "Kimi K3 Technical Report §4.2、§5.3（white-box RL、KG synthesis、AET、Kernel、Personal Assistant、Web development）。",
  },
  "infra-k3": {
    version: "K3",
    title: "Agentic RL 基础设施：为超长轨迹保存状态",
    oneliner: "把 KV 与环境状态分层写回，快速冻结微虚机，并让调度器按运行信号控制并发。",
    problem: ["个人助理轨迹可达百万 token、数千次工具调用；仅把 KV 留在 GPU 会迅速耗尽高带宽显存。", "长程环境若每轮从零重建，前面数百步状态无法复现，失败轨迹也无法低成本续跑。", "policy、reference model 与梯度缓冲同时驻留会放大显存压力，固定并发又会在长尾任务上造成拥塞。"],
    bridge: "不要强迫所有状态常驻最贵的 GPU；让计算、KV、环境和权重各自流向合适层级。",
    mechanism: ["External KV Write-Back Pool 将非活跃 KV 从 GPU 写到 CPU DRAM，再下沉 NVMe；需要续跑时按层级取回。", "AgentENV 基于 Firecracker microVM 保存环境 checkpoint，报告指标约 133 ms checkpoint、49 ms resume，累计创建 5100 万沙箱。", "Auto-throttling scheduler 根据运行时负载动态收缩或扩大并发；Gradient-buffer reuse 暂借 policy 梯度缓冲存放 reference 权重。"],
    visual: { type: "flow", nodes: ["GPU KV", "CPU / NVMe", "AgentENV 快照", "动态调度续跑"], caption: "高价资源只保留正在计算的状态。" },
    formulas: ["KV：GPU → CPU DRAM → NVMe", "checkpoint ≈133 ms；resume ≈49 ms", "policy buffer ⇄ reference weights（分时复用）"],
    example: "例：个人助理完成 800 次工具调用后等待下一模拟日。系统把非活跃 KV 下沉到 DRAM/NVMe，并冻结 microVM；事件到来时先恢复环境，再逐层取回必要 KV，而不是占用一块 GPU 整夜等待。",
    deepDive: ["KV write-back 交换了显存与传输延迟，调度器必须预测哪些轨迹即将恢复。", "Auto-throttling 依据真实运行信号，而非固定批大小，避免慢任务把整个 rollout 集群拖入拥塞。", "133/49 ms 与 5100 万是 K3 系统报告指标，不应外推到任意硬件与环境镜像。"],
    next: "环境和状态管理让九专家可以规模训练；MOPD 随后把九个 checkpoint 合成一个部署模型。",
    source: "Kimi K3 Technical Report §5.3（External KV Write-Back Pool、AgentENV、Auto-throttling、Gradient-buffer reuse）。",
  },
  "reward-k15": {
    version: "K1.5",
    title: "CoT Reward Model",
    oneliner: "让裁判先写出判断过程，再给结构化结论；reward 的可靠性从 84.4% 提升到 98.5%。",
    problem: [
      "规则 verifier 能处理部分数学与代码，但复杂等价变形、自然语言证明仍需要语义判断。",
      "Classic RM 从题目、标准答案和回答直接压成一个分数，容易凭表面形式误判。",
      "RL 会放大 reward 的系统偏差：裁判若持续偏爱某种表面形式，policy 会学会迎合而不是真正解题。",
    ],
    bridge: "既然被训练模型靠长链推理解决难题，裁判也应先推理，再决定这条链是否正确。",
    mechanism: [
      "CoT RM 先生成逐步核验过程：重算关键步骤、检查等价性、寻找反例。",
      "推理结束后输出结构化 JSON 结论，训练管道只读取最终字段，避免自由文本难解析。",
      "人工抽查中 Classic RM 准确率为 84.4%，CoT RM 达到 98.5%；更慢但 reward 噪声显著下降。",
    ],
    visual: { type: "rm-compare" },
    formulas: [
      "Classic：score = RM(x, y*, ŷ)",
      "CoT：z = reason(x,y*,ŷ)，decision = parse(z)",
      "人工抽查 accuracy：84.4% → 98.5%",
    ],
    example: "例：标准答案 a²−4，候选回答 (a+2)(a−2)。Classic RM 可能因字符串差异给低分；CoT RM 先展开乘积得到 a²−4，再输出 {correct:true}。公式等价检查成为判分依据。",
    deepDive: [
      "CoT RM 的代价是每次打分多生成一段推理文本；RL 训练吞吐下降，但错误 reward 造成的方向性损失更昂贵。",
      "可验证任务仍优先使用规则或执行器，CoT RM 补充规则难覆盖的语义边界。",
      "边界：98.5% 来自报告中的人工抽查集，不代表所有任务分布上的普遍准确率。",
    ],
    next: "CoT RM 仍是额外模型，且开放写作没有标准答案可比。K2 改让 policy 自己做 pairwise critique，并用 Rubric 限制它的判断路径。",
    source: "Kimi K1.5 Technical Report §2.3.5（Classic RM 84.4%，CoT RM 98.5%）。",
  },
  "reward-k2": {
    version: "K2",
    title: "Self-Critique Rubric",
    oneliner: "让 policy 比较 A/B 两个回答，但必须沿三层 Rubric 给出可复查理由，而不是凭语气选答案。",
    problem: [
      "创意写作与开放问答没有唯一标准答案，规则 verifier 无法把质量压成简单的 0/1。",
      "单独训练 Reward Model 需要持续收集偏好数据；任务变化后，旧裁判的评分边界也会滞后。",
      "若只问模型“A 和 B 哪个好”，它容易偏爱更长、关键词更多或更像自身写作风格的回答。",
    ],
    bridge: "不再寻找一把万能尺，而是把“好”拆成逐项可检查的判断程序。",
    mechanism: [
      "Core Rubric 检查完整性、逻辑、事实与表达。",
      "Anti-Hack Rubric 单独否决堆词、复读、长度稀释以及机械满足字面约束却绕开真实意图的回答。",
      "Human Rubric 从人工偏好中提取任务特有标准，例如推荐应少而精，而非罗列大量泛化选项。",
      "Closed-Loop Critic 用数学、代码等可验证任务的客观 reward 持续校准自我批评能力。",
    ],
    visual: { type: "rubric" },
    formulas: [
      "s(A)=Σⱼwⱼ·rubricⱼ(A)，s(B)=Σⱼwⱼ·rubricⱼ(B)",
      "preference = 1[s(B) > s(A)]",
      "critic ← calibrate(objective verifier reward)",
    ],
    example: "例：A 给出 20 个泛化旅行建议，B 只给 5 个但逐条匹配用户预算与时间。Core Rubric 判两者都通顺；Anti-Hack 扣除 A 的堆砌；Human Rubric 强调“少而精”，最终 B 胜出。",
    deepDive: [
      "Rubric 是可文本迭代的评分协议，无需每次任务变化都重新训练一个独立 RM。",
      "Closed-Loop 的锚来自可验证域：critic 的判断若与客观结果冲突，就有明确纠偏信号。",
      "边界：可验证域只能校准一致性与推理质量，不能严格证明创意审美偏好也同步变好。",
    ],
    next: "K2 的 critic 仍以文字为主。K2.5 把裁判升级成能同时读文本与图像的 GRM，并给定位、OCR、计数设计连续 reward。",
    source: "Kimi K2 Technical Report §5（Self-Critique、Rubric 与 Closed-Loop Critic）。",
  },
  "reward-k25": {
    version: "K2.5",
    title: "视觉 Reward：GRM 跨模态",
    oneliner: "让同一个能看图也能读文字的裁判统一评分，并让“差一点”和“差很多”产生不同梯度。",
    problem: [
      "文本 RM 与视觉 RM 分开维护时，两套裁判对“好推理”的定义无法共享，跨模态任务也容易落在边界外。",
      "Grounding 若只用是否命中做 0/1 reward，预测框偏 2 像素和偏半张图会收到同样惩罚。",
      "两个框完全不相交时 IoU=0；仅靠 IoU 无法告诉模型应该往哪个方向移动预测框。",
    ],
    bridge: "裁判既要看懂两种输入，又要把几何距离、文字差异与任务正确性变成可比较的连续信号。",
    mechanism: [
      "GRM 本身是 VLM，同一模型读取文本或图像，并用统一推理标准评价候选输出。",
      "Grounding 组合 IoU-F1 与高斯软匹配；多边形分割先光栅化为像素 mask，再计算 mask IoU。",
      "OCR 用归一化编辑距离，计数用绝对差值；开放视觉谜题无法写规则时，由 K2 作为 LLM verifier。",
      "连续 reward 保留误差方向与幅度：接近目标的答案得到部分信用，远离目标的答案受到更大惩罚。",
    ],
    visual: { type: "grm" },
    formulas: [
      "r(task) = rgrounding | rOCR | rQA（按任务类型切换，不做简单平均）",
      "rgrounding = IoU + soft(center distance)",
      "rOCR = 1 − edit(ŷ,y*) / max(|ŷ|,|y*|)",
      "rQA = K2 LLM verifier score；接近目标 ≠ 全错",
    ],
    example: "例：三条不同任务轨迹分别得到 Grounding IoU=0.68、OCR=0.90、开放问答 reward=0.80；0.80 是第三条轨迹的任务分数，不是把前两项平均后得到。",
    deepDive: [
      "IoU 描述重叠质量，高斯软匹配补足不重叠区域的稠密反馈，两者职责不同。",
      "多目标定位用 F1 同时约束 precision 与 recall；不规则多边形光栅化后把几何交集转为像素计数。",
      "归一化编辑距离避免长文本天然积累更多字符错误，使不同长度 OCR 输出可比较。",
      "边界：统一 GRM 共享评分框架不等于所有任务共用同一公式；开放谜题的 LLM verifier 也仍有模型偏差。",
    ],
    next: "统一裁判仍可能跳过阅读直接给分。K3 把评价过程改成强制四步协议，让每个结论都留下 Rubric 与 Scorepad。",
    source: "Kimi K2.5 Technical Report §3（joint multimodal RL 与 visual reward design）。",
  },
  "reward-k3": {
    version: "K3",
    title: "Agentic GRM 四步",
    oneliner: "先完整读轨迹，再动态生成本任务的检查项；逐项留证后才汇总，长度成本单独结算。",
    problem: [
      "K2 的 Self-Critique 有 Rubric，但流程仍较自由；模型可能跳过完整阅读，直接输出偏好结论。",
      "Agent 轨迹包含工具调用、观察与修正，最终答案看似正确也可能掩盖中途伪造或漏执行。",
      "长回答常显得更周全，裁判若不单独约束冗余，会把耗费更多 token 误当作质量更高。",
    ],
    bridge: "把评价变成一条不能跳步的执行协议，并把内容质量与长度成本分开检查。",
    mechanism: [
      "Read：完整读取输出并摘要；Rubric：针对当前任务动态生成检查项。",
      "Score：逐项给 pass/fail 与理由；Scorepad：结构化记录所有判断后才汇总最终 reward。",
      "冗长度规则单独比较回答长度与参考长度；超过 σ·ℓ₀ 时施加负向信号，避免内容得分掩盖浪费。",
    ],
    visual: { type: "agentic-grm" },
    formulas: [
      "steps = Read → Rubric(x) → Scoreⱼ → Scorepad",
      "rquality = Σⱼwⱼ·passⱼ",
      "r = rquality − λ·1[len(ŷ) > σ·ℓ₀]",
    ],
    example: "例：用户要求“查官方文档后给迁移步骤”。裁判先确认轨迹确实调用检索工具，再生成“来源、版本、步骤完整性”三项 Rubric，逐项记录 1/0/1。若回答长于参考的 1.5 倍，还会单独触发冗长度惩罚。",
    deepDive: [
      "动态 Rubric 针对当前实例生成；它比固定模板更能覆盖工具轨迹中特有的完成条件。",
      "Scorepad 的价值是留下机器可解析的中间判断，使训练管道能定位是哪一项失分。",
      "边界：σ=1.5 是页面用于解释的示例阈值；报告机制明确，但不应把示例数值视为所有域的统一配置。",
    ],
    next: "Reward 演进闭环后，下一条主线是长度：从 K1.5 的相对软惩罚，到 K2 硬预算、K2.5 Toggle，再到 K3 的按题 τ 课程。",
    source: "Kimi K3 Technical Report §4.1（Agentic GRM、四步评估协议与 verbosity penalty）。",
  },
  "length-k15": {
    version: "K1.5",
    title: "Length Penalty",
    oneliner: "先让模型学会长链探索，再在同题采样中奖励更短的正确链、惩罚更长的错误链。",
    problem: [
      "结果奖励只关心最终对错；模型会发现多写若干尝试有时更容易碰到正确答案，于是输出持续变长。",
      "一开始就强压长度会截断“走错—发现—回退”的学习，模型尚未获得能力就先学会仓促结束。",
      "对错误短答给额外奖励也不合理：它只是在更快地答错，并没有产生可保留的行为。",
    ],
    bridge: "长度信号要晚于能力出现，并且根据答案是否正确采用不同方向。",
    mechanism: [
      "同题采样 k 条回答，用本组 min_len 与 max_len 把长度映射为 λ：越短越正，越长越负。",
      "正确回答直接加 λ；错误回答只取 min(0,λ)，因此短错答不获奖励，长错答继续受罚。",
      "penalty 先 warmup，再在后期固定加入：先探索出长链能力，再压缩冗余。",
    ],
    visual: { type: "length-penalty" },
    formulas: [
      "λᵢ = 0.5 − (lenᵢ−min_len)/(max_len−min_len)",
      "rlen(correct)=λᵢ",
      "rlen(wrong)=min(0,λᵢ)",
    ],
    example: "例：同题回答长度范围 500–2000；某条长度 1500，则 λ=0.5−1000/1500≈−0.17。若答对，总 reward 扣 0.17；若答错，同样扣 0.17。长度 700 的正确答案获得正奖励，但长度 700 的错误答案只得 0。",
    deepDive: [
      "这是同题采样内的相对软约束，不是部署时固定 token 上限。",
      "warmup 把“先学会、再变短”拆成两个阶段，避免长度目标压过早期探索。",
      "边界：长度更短不等于推理更好；该信号必须与正确性 reward 共同使用。",
    ],
    next: "相对惩罚只能让一组回答彼此变短，不能保证最坏情况不越界。K2 因而加入按任务类型设置的绝对 Budget。",
    source: "Kimi K1.5 Technical Report §2.3.3（Length Reward 与 warmup）。",
  },
  "length-k2": {
    version: "K2",
    title: "Budget Control",
    oneliner: "按任务类型设置绝对 token 上限；越界轨迹被截断，给最坏计算成本一个硬边界。",
    problem: [
      "K1.5 的相对长度奖励只能让同题回答互相比较，整组回答仍可能都非常长。",
      "数学、代码、工具调用的自然轨迹长度差异大；统一上限会浪费简单题预算，又截断复杂工具任务。",
      "线上推理需要可预测的最坏成本，仅靠软 penalty 不能保证单条 rollout 不越界。",
    ],
    bridge: "把“尽量短”升级为“不同任务各有一条不可穿过的停止线”。",
    mechanism: [
      "按任务类型配置 rollout 上限；工具任务因多轮行动—观察通常获得更宽预算。",
      "超过上限后生成被截断，无法形成完整答案；任务 reward 归零，叠加长度惩罚时可得到更强负信号。",
      "硬预算与软 penalty 并用：前者保证边界，后者在边界内部继续鼓励效率。",
    ],
    visual: { type: "budget" },
    formulas: [
      "ŷ = truncate(sample(πθ), Btask)",
      "rtask = 0　if len(ŷ) ≥ Btask 且未完成",
      "Bmath < Bcode < Btool",
    ],
    example: "例：一条工具轨迹在第 18K token 完成。给它 20K 上限可以保留结果；若误用数学任务的 8K 上限，轨迹在关键调用前被截断，最终 reward=0。预算是任务约束，不是回答质量本身。",
    deepDive: [
      "硬截断把最坏 token 成本变得可控，这是相对长度奖励无法提供的系统保证。",
      "任务完成与触顶必须区分：刚好在上限前完整结束可得分，未完成截断才失去任务 reward。",
      "边界：模型可能学会在边界前写出看似完整的仓促结论；这正是 K2.5 Toggle 要修复的长度过拟合。",
    ],
    next: "硬边界控制了成本，却把“在截止线前收尾”变成可利用模式。K2.5 用 Toggle 反复放开与收紧，迫使模型先保证正确再压缩。",
    source: "Kimi K2 Technical Report §4（Budget Control 与长度约束）。",
  },
  "length-k25": {
    version: "K2.5",
    title: "Toggle",
    oneliner: "在“充分推理”和“预算压缩”之间反复切换：准确率先过线，才允许长度目标接管。",
    problem: [
      "K2 的硬上限始终存在，模型可能学到“接近边界就收尾”，而不是更高效地完成推理。",
      "难题需要更长探索；若压缩目标与正确性从第一步同时竞争，模型可能牺牲能力换取更短输出。",
      "完全取消预算又会恢复 overthinking，平均 token 成本重新上升。",
    ],
    bridge: "不要同时要求会做和做短；先让正确率站稳，再短暂施压，掉下阈值就立即松开。",
    mechanism: [
      "Standard Scaling 阶段不加长度预算，让模型充分探索并恢复任务准确率。",
      "Budget-Limited 阶段只在准确率高于阈值 λ 时启用；低于 λ 就取消约束，防止能力继续受损。",
      "两阶段按训练周期反复切换，使模型逐步找到更短但仍能完成任务的轨迹。",
    ],
    visual: { type: "toggle" },
    formulas: [
      "budget_on(t)=1[phase=limited ∧ acc(t)≥λ]",
      "if acc(t)<λ：budget_on(t)←0",
      "优化顺序：correctness → compression → recheck",
    ],
    example: "例：第 1–3 轮无预算，准确率从 72% 升到 84%；阈值 λ=80% 后进入压缩。第 5 轮准确率跌到 78%，预算自动关闭；第 6 轮充分推理恢复到 83%，下一轮再尝试压缩。",
    deepDive: [
      "Toggle 的核心不是固定交替，而是预算阶段受准确率条件保护。",
      "它与 K2 的区别是：K2 绝对不能越界；Toggle 在能力不足时允许重新展开推理。",
      "边界：页面中的轮次与准确率用于逐帧解释，不是报告披露的统一训练超参数。",
    ],
    next: "Toggle 仍是全局阶段开关。K3 进一步为每道题估计基准长度 b₀(x)，再用 τ 按域、按 effort 逐步收紧。",
    source: "Kimi K2.5 Technical Report §3（Toggle mechanism 与 length optimization）。",
  },
  "length-k3": {
    version: "K3",
    title: "τ 退火",
    oneliner: "先用 b₀(x) 估计每道题自身需要多长，再用 τ 按任务域与 effort 缩放预算。",
    problem: [
      "Toggle 解决了何时压缩，却仍以训练阶段为全局开关；同一阶段内，简单题与难题受到相似约束。",
      "General Tasks 一次输出即可，Coding Agents 需要编译—报错—修复循环，天然 token 需求不同。",
      "直接训练 low effort 会把“不会展开”误当成“高效率”，难题能力在形成前就被剪掉。",
    ],
    bridge: "先问这道题本来需要多少，再决定当前 effort 允许它放大几倍。",
    mechanism: [
      "冷启动模型为题目 x 产生基准轨迹长度 b₀(x)，它保留题目难度的个体差异。",
      "预算上限由 τ·b₀(x) 给出；训练先用较宽松 max，再退火到 high、low。",
      "τ 按任务域配置：Coding Agents 的交互循环通常比 General Tasks 获得更宽松倍数。",
    ],
    visual: { type: "tau" },
    formulas: [
      "B(x,domain,effort)=τdomain,effort·b₀(x)",
      "τmax > τhigh > τlow",
      "len(ŷ)>B(x,·) → length penalty",
    ],
    example: "例：冷启动模型对简单问答给 b₀=200，对代码修复给 b₀=4000。即使同为 high effort，若示意 τtask=1.5、τcode=2.0，上限分别为 300 与 8000；预算同时适配题目和任务域。",
    deepDive: [
      "与 K2 固定任务上限相比，b₀(x) 让同一域内部的不同题目也拥有不同预算。",
      "max→high→low 是课程顺序：先获得充分解决能力，再学习在更小预算中保留关键行为。",
      "边界：页面示例中的 τ 数值仅用于代入演示；K3 报告没有披露统一的精确取值。",
    ],
    next: "四代长度控制至此完成。RL 专项还剩五张：无 value network、Long2Short、PTX、MOPD 与 QAT + EAGLE-3。",
    source: "Kimi K3 Technical Report §4.1（Reasoning Effort RL、domain-specific budget 与 annealing）。",
  },
  "rl-k15-value": {
    version: "K1.5",
    title: "无 value network",
    oneliner: "不急着评价每个中间念头；只要整条链最终纠错成功，就让探索与回退行为一起被保留。",
    problem: [
      "长链推理不是每一步都朝正确答案直线前进；试错、反例和回退往往是找到解法的一部分。",
      "中间 value 若把暂时错误判成低价值，会在模型尚未展示纠错能力前就削弱这段轨迹。",
      "训练另一个 value network 还会引入估计误差和额外计算，且长链每一步缺少人工真值。",
    ],
    bridge: "既然真正可验证的是最终结果，就先把整条回答当作最小学习单元。",
    mechanism: [
      "同题采样多条完整回答，只在结束后用最终答案或测试结果计算 reward。",
      "组内均值作为 baseline，让正确链获得正 advantage、错误链获得负 advantage。",
      "一条先错后改的正确链整体被提高概率；训练信号不会单独惩罚其中的探索节点。",
    ],
    visual: { type: "value-free" },
    formulas: [
      "r(y)=verifier(final(y))",
      "Aⱼ=rⱼ−mean(r₁…rₖ)",
      "不估计 V(x,y<t)：credit assignment = whole trajectory",
    ],
    example: "例：模型先假设 n 为偶数，推到矛盾后回退改用奇偶分类，最终证明成立。逐步 value 可能在“错误假设”处给负分；整链 reward=1 则把发现矛盾并修正的能力一并保留。",
    deepDive: [
      "无 value network 不等于无 baseline；K1.5 仍用同题样本的平均 reward 降低方差。",
      "它牺牲精细的步骤归因，换取对开放式探索路径更少的先验干预。",
      "边界：整链奖励也会把无用绕路一起强化，因此必须再配合 Length Penalty 做后期压缩。",
    ],
    next: "保住探索后，部署成本仍太高。Long2Short 用四种由弱到强的方法，把长链能力压回更短输出。",
    source: "Kimi K1.5 Technical Report §2.3.2（value-free RL 与 group-relative baseline）。",
  },
  "rl-k15-l2s": {
    version: "K1.5",
    title: "Long2Short",
    oneliner: "从合并权重到重新做 RL，四种方法逐级增强“保留正确性、删除冗余路径”的监督。",
    problem: [
      "Long-CoT RL 激发了探索与纠错，但部署时每题都生成长链会放大延迟与 token 成本。",
      "直接要求模型“回答简短”可能把推理步骤和真正能力一起删掉。",
      "单一压缩方法难兼顾训练成本与效果，因此报告比较了由轻到重的四条路线。",
    ],
    bridge: "先确认哪部分能力能零成本迁移，再逐步加入短正确样本、负样本和真实策略优化。",
    mechanism: [
      "Weight Merge：直接平均 long/short checkpoint，成本最低；它只做权重插值，不显式识别哪些 token 冗余。",
      "Shortest Rejection Sampling：同题采样多次，只保留最短正确链作为 SFT 样本，让模型模仿自身自然出现的短解。",
      "DPO：把最短正确链设为 positive，把明显更长的链设为 negative，显式学习“短正确优于冗长”。",
      "Long2Short RL：缩短最大 rollout 上限并叠加 Length Penalty；超时链拿不到任务 reward，在线逼迫模型在预算内完成推理。",
    ],
    visual: { type: "long2short" },
    formulas: [
      "θmerge = α·θlong + (1−α)·θshort",
      "y+ = argminlen{y：verifier(y)=1}",
      "DPO(y+≻y−) → RL with reduced budget",
    ],
    example: "例：同题 8 次采样得到 4 条正确链，长度为 1800/1200/900/700。Shortest RS 只用 700-token 链做 SFT；DPO 进一步把 1800-token 正确链作为反例；RL 则让学生自己生成，越界就失去奖励。",
    deepDive: [
      "四法的核心区别是训练数据来自教师轨迹还是学生当前策略，以及是否提供显式负样本。",
      "On-policy RL 最贴近部署分布，但训练成本和稳定性要求也最高。",
      "边界：最短正确链不一定是最清晰链；压缩时仍需用正确性与可读性信号守住下限。",
    ],
    next: "K1.5 解决了长链与压缩；K2 把能力扩到更多任务后，又出现通用能力遗忘，PTX Loss 用少量 SFT 样本持续锚定。",
    source: "Kimi K1.5 Technical Report §2.4（Long2Short 的 Weight Merge、Shortest RS、DPO 与 RL）。",
  },
  "rl-k2-ptx": {
    version: "K2",
    title: "PTX Loss（Pre-Training Loss，预训练损失）",
    oneliner: "PTX 是预训练损失：在 RL batch 里加入少量高质量 SFT 样本，用 next-token loss 保留未采样能力。",
    problem: [
      "RL 数据集中在数学、代码与工具任务；写作、百科解释等能力长期收不到正向梯度。",
      "参数由所有任务共享，专项 RL 更新可能改变通用语言分布，造成灾难性遗忘。",
      "完全回到 SFT 又会压制刚学到的探索和工具行为，需要的是弱锚定而非重新训练。",
    ],
    bridge: "让每个专项更新旁边都出现少量通用示范，持续告诉模型哪些旧行为不能漂走。",
    mechanism: [
      "每个 RL batch 混入少量高质量 SFT 样本，覆盖解释、写作与常识等多样任务。",
      "RL 样本计算策略目标；SFT 样本计算标准 next-token prediction loss，二者加权求和。",
      "α 保持较小，只负责抵抗遗忘，不让模仿损失淹没新能力的 RL 信号。",
    ],
    visual: { type: "ptx" },
    formulas: [
      "Ltotal = LRL + α·LPTX",
      "LPTX = −Σₜlog πθ(yₜ|x,y<t)",
      "α ≪ 1：anchor，不是主目标",
    ],
    example: "例：一个 32 样本 batch 以工具 RL 为主，同时加入 2 条高质量解释型 SFT。工具轨迹仍决定主要更新方向；若更新开始破坏正常说明文字，PTX 的 next-token loss 会提供反向拉力。",
    deepDive: [
      "PTX 样本不需要 reward；它们用教师答案直接计算 token 级交叉熵。",
      "这和 KL 锚定不同：KL 约束新旧策略整体距离，PTX 明确重放希望保留的行为样本。",
      "边界：α 过大会使模型退回 SFT 风格、削弱探索；过小则不足以抵抗遗忘，需要按训练配方标定。",
    ],
    next: "K2 的能力锚定完成后，K3 的问题变成如何把九个专门化教师合回一个模型；MOPD 让学生走自己的轨迹并逐 token 接受教师信号。",
    source: "Kimi K2 Technical Report §4（PTX loss 与 RL recipe）。",
  },
  "rl-k3-mopd": {
    version: "K3",
    title: "MOPD",
    oneliner: "学生沿自己的分布生成，九位教师在每个 token 给稠密方向信号，最终合成一个可部署模型。",
    problem: [
      "三域×三强度得到九个专门化 checkpoint，但部署时同时维护九个完整模型成本过高。",
      "普通 off-policy 蒸馏让学生模仿教师生成的标准轨迹；部署时学生一旦走到教师未覆盖的状态，指导就中断。",
      "只在整条轨迹结束后给 0/1 reward 太稀疏，难以告诉学生具体哪个 token 更接近专家行为。",
    ],
    bridge: "让学生先暴露自己真实会走的路，再把教师意见投射到这条路的每一个位置。",
    mechanism: [
      "学生 on-policy 逐 token 生成；当前任务对应的教师在相同前缀上给出 token 概率。",
      "教师比学生更偏好已生成 token 时给正 reward，反之给负 reward；clip 限制极端概率差。",
      "教师端 stop-gradient 保持冻结；完整轨迹结束后，学生结合整链 RL reward 与 token-level MOPD reward 更新。",
    ],
    visual: { type: "mopd" },
    formulas: [
      "rₜ=clip(sg(log πT(yₜ|hₜ)−log πθ(yₜ|hₜ)),−Rmax,Rmax)",
      "Rtotal = Rtask + β·Σₜrₜ",
      "trajectory y ∼ πθ　(on-policy)",
    ],
    example: "例：学生在代码修复中生成 token `pytest`。Coding-max 教师给概率 0.60，学生仅给 0.20，则 log(0.60)−log(0.20)=log 3，为正反馈；后续学生更倾向在相似状态选择该工具。",
    deepDive: [
      "on-policy 保证训练前缀来自学生自身分布，教师是在学生真实薄弱处给反馈。",
      "sg 不是冻结学生梯度，而是阻断教师概率被反向更新；教师始终保持专家水平。",
      "边界：教师可能不偏好另一条同样正确的路径；整链任务 reward 必须保留，以免局部模仿压掉路径多样性。",
    ],
    next: "学生合一后，部署速度还受低精度推理与逐 token 解码限制。K3 在 SFT/RL 全程做 QAT，并把 MTP 层改造成 EAGLE-3 draft。",
    source: "Kimi K3 Technical Report §4.1.3，Eq. (15)（Multi-Teacher On-Policy Distillation）。",
  },
  "rl-k3-eagle": {
    version: "K3",
    title: "Draft Model Fine-tuning：EAGLE-3",
    oneliner: "MOPD 改变了主模型分布；最后只微调 MTP draft 层，把 acceptance rate 补回来，再进入部署。",
    problem: [
      "自回归解码每生成一个 token 都要读取一次大模型权重，常受内存带宽而非算力限制。",
      "独立小 draft 若与主模型分布差异大，猜测频繁被拒绝，并行验证带来的收益会消失。",
      "只优化 draft 的 next-token 准确率不够；真正决定吞吐的是候选被 target model 接受的概率。",
    ],
    bridge: "既然预训练已有 MTP 头，就不再训练第二个完整模型，而是把它直接对齐到主模型的验收规则。",
    mechanism: [
      "EAGLE-3 由预训练 MTP 层微调，融合主模型低/中/高层特征，快速提出 k 个候选 token。",
      "主模型一次并行验证候选；L_LK 直接缩小 draft 与主模型分布差异，以提升 acceptance rate。",
      "候选未通过时回退到主模型分布，因此推测解码加速生成，但不改变 target model 的输出分布。",
    ],
    visual: { type: "eagle" },
    formulas: [
      "P(连续 k 个全接受)=pᵏ",
      "E[accepted] 上限 ≈ 1/(1−p)",
      "LLK：min D(distributiondraft, distributiontarget)",
    ],
    example: "例：若每 token 接受率 p=0.9，几何期望上限约 1/(1−0.9)=10 个；p=0.7 时仅约 3.3 个。把 p 从 0.7 提到 0.9，收益并非线性增加，因此训练目标直接对齐分布接受率。",
    deepDive: [
      "推测解码保持主模型输出分布，不是用 draft 直接替代主模型；未通过的候选会被拒绝并回退。",
      "k 不是越大越好：整段全接受概率 pᵏ 随长度指数下降，存在吞吐最优点。",
      "边界：3.3×/10×是几何期望上限的教学值，不是 K3 报告公布的端到端实测加速倍数。",
    ],
    next: "至此整页闭环：SFT 建立低精度冷启动，九专家分化能力，MOPD 合一，最后由 EAGLE-3 降低自回归解码延迟。",
    source: "Kimi K3 Technical Report §4.1.4（Draft Model Fine-Tuning / EAGLE-3）。",
  },
});
